### ISSUE TITLE
Image component returns relative paths on build

### ISSUE THREAD

**Issue by preetamslot** [RafidMuhymin/astro-image-demo#5]
`src="assets/pexels-kumar-saurabh-1456613@5184w.b934caf6.jpeg"`
should be
`src="/assets/pexels-kumar-saurabh-1456613@5184w.b934caf6.jpeg"`

**Comment by RafidMuhymin** [comment]
Thank you @preetamslot! Yeah, I'm confirming this.

**Comment by RafidMuhymin** [comment]
@preetamslot `v0.0.10` should fix this issue. Can you check?

**Comment by preetamslot** [comment]
When I clone this project and run dev I get the following error:

```
03:17 PM [astro] Server started                               675ms
03:17 PM [astro] Local: http://127.0.0.1:3001/
3:17:27 PM [vite] Error when evaluating SSR module /node_modules/astro-imagetools/src/component/utils/getImage.js:
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (C:\SITES\astro-image-test\node_modules\vite\dist\node\chunks\dep-1412e872.js:56171:28)
3:17:27 PM [vite] Error when evaluating SSR module /node_modules/astro-imagetools/src/component/utils/renderImage.js:
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (C:\SITES\astro-image-test\node_modules\vite\dist\node\chunks\dep-1412e872.js:56171:28)
3:17:27 PM [vite] Error when evaluating SSR module /node_modules/astro-imagetools/src/component/Image.astro: 
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (C:\SITES\astro-image-test\node_modules\vite\dist\node\chunks\dep-1412e872.js:56171:28)
3:17:27 PM [vite] Error when evaluating SSR module C:\SITES\astro-image-test\src\pages\index.astro:
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (C:\SITES\astro-image-test\node_modules\vite\dist\node\chunks\dep-1412e872.js:56171:28)
03:17 PM [astro] 500 /
03:17 PM [astro] 404 /favicon.ico
```

on build :
```

> @ build C:\SITES\astro-image-test
> astro build

03:19 PM [config] Set "buildOptions.site" to generate correct canonical URLs and sitemap
3:19:23 PM [vite] Error when evaluating SSR module /node_modules/astro-imagetools/src/component/utils/getImage.js:
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (C:\SITES\astro-image-test\node_modules\vite\dist\node\chunks\dep-1412e872.js:56171:28)
3:19:23 PM [vite] Error when evaluating SSR module /node_modules/astro-imagetools/src/component/utils/renderImage.js:
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (C:\SITES\astro-image-test\node_modules\vite\dist\node\chunks\dep-1412e872.js:56171:28)
3:19:23 PM [vite] Error when evaluating SSR module /node_modules/astro-imagetools/src/component/Image.astro: 
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (C:\SITES\astro-image-test\node_modules\vite\dist\node\chunks\dep-1412e872.js:56171:28)
3:19:23 PM [vite] Error when evaluating SSR module C:\SITES\astro-image-test\src\pages\index.astro:
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (C:\SITES\astro-image-test\node_modules\vite\dist\node\chunks\dep-1412e872.js:56171:28)
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (C:\SITES\astro-image-test\node_modules\vite\dist\node\chunks\dep-1412e872.js:56171:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `astro build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\preet\AppData\Roaming\npm-cache\_logs\2022-02-13T14_19_23_321Z-debug.log
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run build" terminated with exit code: 1.
```

**Comment by preetamslot** [comment]
If I update to v0.1.0 
Then I get the following error :

```
@ dev C:\SITES\astro-image-test
> astro dev

(node:27452) UnhandledPromiseRejectionWarning: Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\SITES\astro-image-test\node_modules\astro-imagetools\plugin' imported from C:\SITES\astro-image-test\astro.config.mjs 
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)        
(node:27452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by preetamslot** [comment]
Fixed it by starting using the Astro documentation, installing the plugin, and upgrading to the latest Astro next version.
